export const exchangeProducts = [
  {
    id: 1,
    image: "./images/p1.png",
    title: "Winter Wasket",
    price: 999,
    address: "Dara Adam Khel, Kohat",
    createdAt: "2 days ago",
    status: "exchange",
    condition: "New",
  },
  {
    id: 2,
    image: "./images/p2.jpg",
    title: "Apple Blutooth",
    price: 1200,
    address: "Khyali kor Suran, Mohmand Agency",
    createdAt: "today",
    status: "exchange",
    condition: "Used",
  },
  {
    id: 3,
    image: "./images/p3.jpg",
    title: "Smart Speaker",
    price: 1500,
    address: "Pabbi Station, Nowshehra",
    createdAt: "3 days ago",
    status: "exchanged",
    condition: "Used",
  },
  {
    id: 4,
    image: "./images/p4.jpg",
    title: "DSLR Camera 12x",
    price: 75000,
    address: "Taro Jaba, Peshawar",
    createdAt: "yesterday",
    status: "exchanged",
    condition: "Used",
  },
  {
    id: 5,
    image: "./images/p5.jpg",
    title: "Winter Wasket",
    price: 999,
    address: "Dara Adam Khel, Kohat",
    createdAt: "2 Days ago",
    status: "exchange",
    condition: "New",
  },
  {
    id: 6,
    image: "./images/p6.jpg",
    title: "Iphone 13 Pro-Max",
    price: 150000,
    address: "Gul Haji Plaza, Peshawar s vas asd as asdsd",
    createdAt: "5 Days ago",
    status: "exchanged",
    condition: "New",
  },
  {
    id: 7,
    image: "./images/p3.jpg",
    title: "Smart Speaker",
    price: 1500,
    address: "Pabbi Station, Nowshehra",
    createdAt: "3 days ago",
    status: "exchange",
    condition: "New",
  },
];
